name: 'Create Black Duck report'
description: 'Create Black Duck report'
author: 'Tiago Santos'

branding:
  icon: 'settings'
  color: 'blue'

inputs:
  blackduck-url:
    description: 'Black Duck instance URL'
    required: true
  blackduck-token:
    description: 'Black Duck API token'
    required: true
  output-directory:
    description: 'Path to the directory where the report will be saved'
    default: './blackduck-report'
    required: false
  project-name:
    description: 'Project name in Black Duck'
    required: false
    default: ${{ github.repository }}
  project-version:
    description: 'Project version in Black Duck'
    required: false
    default: ${{ github.ref_name }}
  report-format:
    description: |-
      Report format depending on report-type. The following values are supported:
      - SPDX_22 report: JSON, YAML, RDF or TAGVALUE.
      - SPDX_23 report: JSON, YAML, RDF or TAGVALUE.
      - CYCLONE_DX_13 report: JSON.
      - CYCLONE_DX_14 report: JSON.
      - LICENSE report: JSON or TEXT.
    default: 'JSON'
    required: false
  report-type:
    description: |-
      Report type. The following values are supported:
      - SPDX_22. Generate a SBOM SPDX v2.2 report.
      - SPDX_23. Generate a SBOM SPDX v2.3 report.
      - CYCLONE_DX_13. Generate a SBOM CycloneDX v1.3 report.
      - CYCLONE_DX_14. Generate a SBOM CycloneDX v1.4 report.
      - LICENSE. Generate a license report.
    default: 'SPDX_23'
    required: false
  sbom-report-template:
    description: |-
      Template name to be used for the SBOM report. This needs to match the name
      of the template in Black Duck. If not provided, the default template will
      be used.
    required: false

outputs:
  report-file-path:
    description: 'Path to the generated report file'

runs:
  using: node20
  main: dist/index.js
